#!/usr/bin/env python3
"""Requirement traceability: which tests prove which requirement (docs/requirements.md).

    scripts/req_coverage.py            write docs/traceability.md
    scripts/req_coverage.py --check    also fail (exit 1) if a requirement has no test
    scripts/req_coverage.py --stdout   print instead of writing

Tests name their requirements like this:
    server/tests/*.py        @test("REC-03", "ARC-03")  above the test function
    server/tests/web/*.mjs   test("name", ["REC-02", ...], async () => ...)
    app/test/*.dart          // covers: UX-03, REC-01      on the line(s) above test()/testWidgets()
    scripts/*, *.sh          # covers: SET-01               anywhere in the file (whole file = one check)
Requirements that can only be checked by hand list the procedure in MANUAL below.
"""

import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
REQ_FILE = os.path.join(ROOT, "docs", "requirements.md")
OUT = os.path.join(ROOT, "docs", "traceability.md")
ID = r"[A-Z]{2,5}-\d{2}"

MANUAL = {
    "ARC-07": "Reboot the Pi: `scripts/setup_pi.sh --reboot user@pi` waits for the service after boot.",
    "SEC-01": "Pair a new phone outside and inside the pairing window (`server/tests/bt_pairing_security_test.sh`).",
    "SEC-02": "`server/tests/bt_pairing_security_test.sh`: an untrusted device is refused.",
    "CON-01": "Walk out of Bluetooth range and back: the app reconnects and the shell resumes (also `reconnect_live_test.dart`).",
    "CON-02": "Phone on another Wi-Fi: the Recorder tab explains why there is no picture; same Wi-Fi: live picture.",
}


def requirements():
    reqs = []
    for line in open(REQ_FILE, encoding="utf-8"):
        m = re.match(r"\|\s*(%s)\s*\|\s*(.+?)\s*\|\s*$" % ID, line)
        if m:
            text = re.sub(r"\*\*|`", "", m.group(2))
            short = re.split(r"(?<=[.!?])\s", text, maxsplit=1)[0]
            reqs.append((m.group(1), short[:110] + ("…" if len(short) > 110 else ""),
                         "(withdrawn)" in text))
    return reqs


def ids(s):
    return re.findall(ID, s)


def scan():
    found = {}   # req -> [(suite, test)]

    def add(reqs, suite, name):
        for r in reqs:
            found.setdefault(r, []).append((suite, name))

    tests = os.path.join(ROOT, "server", "tests")
    for f in sorted(os.listdir(tests)):
        p = os.path.join(tests, f)
        if f.endswith(".py"):
            src = open(p, encoding="utf-8").read()
            for m in re.finditer(r"@test\(([^)]*)\)\s*\n\s*def (\w+)", src):
                add(ids(m.group(1)), "server/tests/" + f, m.group(2))
        elif f.endswith(".sh"):
            src = open(p, encoding="utf-8").read()
            for m in re.finditer(r"#\s*covers:\s*(.+)", src):
                add(ids(m.group(1)), "server/tests/" + f, "(script)")
    web = os.path.join(tests, "web")
    if os.path.isdir(web):
        for f in sorted(os.listdir(web)):
            if f.endswith((".mjs", ".js")) and f != "package-lock.json":
                src = open(os.path.join(web, f), encoding="utf-8").read()
                for m in re.finditer(r'test\("(\w+)",\s*\[([^\]]*)\]', src):
                    add(ids(m.group(2)), "server/tests/web/" + f, m.group(1))
    dart = os.path.join(ROOT, "app", "test")
    for f in sorted(os.listdir(dart)) if os.path.isdir(dart) else []:
        if not f.endswith(".dart"):
            continue
        lines = open(os.path.join(dart, f), encoding="utf-8").read().splitlines()
        pending = []
        for line in lines:
            m = re.search(r"//\s*covers:\s*(.+)", line)
            if m:
                pending += ids(m.group(1))
                continue
            t = re.search(r"\b(?:testWidgets|test)\(\s*'([^']+)'", line)
            if t and pending:
                add(pending, "app/test/" + f, t.group(1))
                pending = []
    scripts = os.path.join(ROOT, "scripts")
    for f in sorted(os.listdir(scripts)):
        p = os.path.join(scripts, f)
        if os.path.isfile(p) and f != os.path.basename(__file__):
            for m in re.finditer(r"#\s*covers:\s*(.+)", open(p, encoding="utf-8", errors="replace").read()):
                add(ids(m.group(1)), "scripts/" + f, "(script)")
    return found


def render(reqs, found):
    known = {r for r, _, _ in reqs}
    live = [r for r in reqs if not r[2]]
    covered = [r for r, _, _ in live if found.get(r)]
    manual_only = [r for r, _, _ in live if not found.get(r) and r in MANUAL]
    missing = [r for r, _, _ in live if not found.get(r) and r not in MANUAL]
    out = ["# Traceability", "",
           "Generated by `scripts/req_coverage.py` from the test sources - do not edit by hand.", "",
           "%d requirements: %d with automated tests, %d checked by hand, %d without any check."
           % (len(live), len(covered), len(manual_only), len(missing)), ""]
    unknown = sorted(set(found) - known)
    if unknown:
        out += ["**Tests name unknown requirements:** " + ", ".join(unknown), ""]
    out += ["| ID | Requirement | Tests |", "|---|---|---|"]
    for r, text, withdrawn in reqs:
        if withdrawn:
            out.append("| %s | %s | (withdrawn) |" % (r, text))
            continue
        cells = ["`%s` %s" % (s, n) for s, n in found.get(r, [])]
        if r in MANUAL:
            cells.append("manual: " + MANUAL[r])
        out.append("| %s | %s | %s |" % (r, text.replace("|", "/"), "<br>".join(cells) or "**none**"))
    return "\n".join(out) + "\n", missing, unknown


def main():
    reqs = requirements()
    text, missing, unknown = render(reqs, scan())
    if "--stdout" in sys.argv:
        sys.stdout.write(text)
    else:
        with open(OUT, "w", encoding="utf-8") as f:
            f.write(text)
        print("wrote %s" % os.path.relpath(OUT, ROOT))
    if missing:
        print("no test for: " + ", ".join(missing))
    if unknown:
        print("tests name unknown requirements: " + ", ".join(unknown))
    if "--check" in sys.argv and (missing or unknown):
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
